services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2024!"
    volumes:
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"